### ISSUE TITLE
怎么获取cookies

### ISSUE THREAD

**Issue by mizhewei** [T3rry7f/Fake115Upload#10]
怎么获取cookies啊

**Comment by xiaokaixuan** [comment]
@mizhewei 浏览器登录后F12 里面复制

**Comment by mizhewei** [comment]
有很多呀，是哪一条，或者搜索哪一个关键词？

**Comment by raddyfiy** [comment]
> 有很多呀，是哪一条，或者搜索哪一个关键词？
在115浏览器登陆后按F12，再按F5刷新一次，在Network里点击最上面一条，找到request headers区域，把cookie冒号后面的复制下来，粘到程序里的引号内。
