### ISSUE TITLE
请问加密是如何逆向的？

### ISSUE THREAD

**Issue by ODtian** [T3rry7f/Fake115Upload#14]
是通过抓包吗，我没有抓到

**Comment by T3rry7f** [comment]
> 是通过抓包吗，我没有抓到

算法实现在可执行文件里 直接逆向浏览器主程序就能找到了

**Comment by ODtian** [comment]
请问加密和不加密上传时有区别吗

**Comment by T3rry7f** [comment]
> 请问加密和不加密上传时有区别吗

官方对参数校验不严格 且不同平台实现的接口不一致 加密的是最新pc版接口的模拟  感兴趣的话可以自己的逆下手机端的看看有什么区别
