### ISSUE TITLE
m115加密是在什么时候被使用

### ISSUE THREAD

**Issue by 592767809** [T3rry7f/Fake115Upload#15]
我在代码中没有找打get_download_url_by_pc函数被调用的时候，请问这个方法传入的pc参数是在哪里来的？我直接调用这个函数，传入文件的pc值，却得到{'state': False, 'msg': '很抱歉，提取码不能为空。', 'errno': 50001}

**Comment by T3rry7f** [comment]
> 我在代码中没有找打get_download_url_by_pc函数被调用的时候，请问这个方法传入的pc参数是在哪里来的？我直接调用这个函数，传入文件的pc值，却得到{'state': False, 'msg': '很抱歉，提取码不能为空。', 'errno': 50001}

115专用下载链接获取接口 有别于第三方浏览器

**Comment by 592767809** [comment]
> > 我在代码中没有找打get_download_url_by_pc函数被调用的时候，请问这个方法调用的pc参数是在哪里来的？我直接调用这个函数，放入文件的pc值，却得到{'state'：False， 'msg'：'很抱歉，提取码不能为空。'，'errno'：50001}
> 
> 115专用下载链接获取接口有别于第三方浏览器

请问115专用下载链接是在哪个客户端使用的？我在PC端的115浏览器（23.9.2.1），安卓APP（26.2.1）都不是使用的这个接口

**Comment by yusilong** [comment]
> > 我在代码中没有找打get_download_url_by_pc函数被调用的时候，请问这个方法传入的pc参数是在哪里来的？我直接调用这个函数，传入文件的pc值，却得到{'state': False, 'msg': '很抱歉，提取码不能为空。', 'errno': 50001}
> 
> 115专用下载链接获取接口 有别于第三方浏览器

这个接口返回的是乱码，
![image](https://user-images.githubusercontent.com/9879307/101205088-3403c500-36a8-11eb-9624-76bab2433f9c.png)
现在win10不能获取sha1了，提示，“你下载的文件大小超出限制，请使用最新115电脑端下载”

**Comment by T3rry7f** [comment]
> > > 我在代码中没有找打get_download_url_by_pc函数被调用的时候，请问这个方法传入的pc参数是在哪里来的？我直接调用这个函数，传入文件的pc值，却得到{'state': False, 'msg': '很抱歉，提取码不能为空。', 'errno': 50001}
> > 
> > 
> > 115专用下载链接获取接口 有别于第三方浏览器
> 
> 这个接口返回的是乱码，
> ![image](https://user-images.githubusercontent.com/9879307/101205088-3403c500-36a8-11eb-9624-76bab2433f9c.png)
> 现在win10不能获取sha1了，提示，“你下载的文件大小超出限制，请使用最新115电脑端下载”

是的 官方已经开始限制第三方工具了 最新的下载接口算法略有改动 问题不大 先缓缓吧 不然开发要骂人了

**Comment by yusilong** [comment]
> > > > 我在代码中没有找打get_download_url_by_pc函数被调用的时候，请问这个方法传入的pc参数是在哪里来的？我直接调用这个函数，传入文件的pc值，却得到{'state': False, 'msg': '很抱歉，提取码不能为空。', 'errno': 50001}
> > > 
> > > 
> > > 115专用下载链接获取接口 有别于第三方浏览器
> > 
> > 
> > 这个接口返回的是乱码，
> > ![image](https://user-images.githubusercontent.com/9879307/101205088-3403c500-36a8-11eb-9624-76bab2433f9c.png)
> > 现在win10不能获取sha1了，提示，“你下载的文件大小超出限制，请使用最新115电脑端下载”
> 
> 是的 官方已经开始限制第三方工具了 最新的下载接口算法略有改动 问题不大 先缓缓吧 不然开发要骂人了

问题不大？老大威武，等待好消息，先消停一段时间

**Comment by iwestlin** [comment]
我调试半天找到了关键函数 `window.browserInterface.CreateDownloadTask`
结果这玩意儿tm是个 `[native code]`，看来是被115套壳的时候封装到浏览器里了。。
大佬能指点下下一步怎么搞吗……

**Comment by T3rry7f** [comment]
> 我调试半天找到了关键函数 `window.browserInterface.CreateDownloadTask`
> 结果这玩意儿tm是个 `[native code]`，看来是被115套壳的时候封装到浏览器里了。。
> 大佬能指点下下一步怎么搞吗……

打开IDA分析即可..

**Comment by delphilite** [comment]
经测试，get_download_url_by_pc 已失效；期待老大好消息 ~
