### ISSUE TITLE
無法使用

### ISSUE THREAD

**Issue by jakzhi104** [T3rry7f/Fake115Upload#16]
安裝了最新版本，但是連接任務中無法顯示轉傳按鈕。

已重啟115瀏覽器，以及是列表模式，但問題依舊。

請問可以解決一下嗎？謝謝

**Comment by T3rry7f** [comment]
> 安裝了最新版本，但是連接任務中無法顯示轉傳按鈕。
> 
> 已重啟115瀏覽器，以及是列表模式，但問題依舊。
> 
> 請問可以解決一下嗎？謝謝

点击导入即可 存储目录同名
