### ISSUE TITLE
请问作者是怎么研究出115下载地址的加密方式呢？能提供一下大体思路吗？

### ISSUE THREAD

**Issue by jbxiaoyu** [T3rry7f/Fake115Upload#17]
RSA通过公钥加密、XOR处理pick_code作为data提交后，返回的data字段再通过私钥解密、XOR处理从而得出真正的下载地址。这是怎么研究出的呢？逆向115浏览器吗？

**Comment by LSD08KM** [comment]
[https://github.com/T3rry7f/Fake115Upload/issues/14](url)
