### ISSUE TITLE
秒传好像失效了

### ISSUE THREAD

**Issue by orzogc** [T3rry7f/Fake115Upload#22]

**Comment by T3rry7f** [comment]
接口更新了吧  换成最新的接口就行

<img width="722" alt="截屏2022-09-29 下午6 49 18" src="https://user-images.githubusercontent.com/10323127/193012876-c5564d9d-b71c-47f7-bc33-4cf523f40be6.png">
  -Test on 115电脑版 Mac版 V2.0.1.7

**Comment by guyueyingmu** [comment]
token 参数是怎么算出来的？

**Comment by orzogc** [comment]
![Screenshot_20220930_014912](https://user-images.githubusercontent.com/6040599/193105498-da312142-d9f8-4ebd-a877-bce3d90c13f8.png)
我运行是这样的，提示要升级到最新版本，难道跟我帐号不是VIP会员有关？

**Comment by T3rry7f** [comment]
昨天简单看了下，虽然加了一点混淆，不过整体加密算法没怎么变化，参考之前的代码很容易就可以找到新的token算法，仅仅是哈希的内容变了。另外转存接口官方应该比谁都懂，虽然现在基本不用这软件了，建议在等等。

**Comment by WertherHu** [comment]
大佬，有没有什么推荐的js逆向教程或者资料？

**Comment by kdurov** [comment]
请教下现在还有什么办法可以非秒传上传么？
堆积在VPS上的文件都快塞得满满的没地方传了😭

**Comment by orzogc** [comment]
`m115_encode`和`m115_decode`好像也失效了
