### ISSUE TITLE
能否指定目录进行上传？

### ISSUE THREAD

**Issue by LittleNewton** [T3rry7f/Fake115Upload#4]
我有一些图片，每个图片对应一个115文件夹，能否根据自定义的[img : folder]键值对进行自定义上传？

**Comment by T3rry7f** [comment]
115是通过CID值来区分目录的，上传前必须先获得文件夹的CID值 ，才可以将文件上传到指定目录，只要把target参数最后数字0改为对于的CID值就可以了，自己修改下程序就可以实现了

**Comment by wywktony** [comment]
> 我有一些图片，每个图片对应一个115文件夹，能否根据自定义的[img：文件夹]键值对进行自定义上传？


> 115是通过CID值来区分目录的，上传前必须先获得文件夹的CID值，才可以将文件上传到指定目录，只要把目标参数最后一个数字0更改为的CID值就可以了，自己修改下程序就可以实现了

大佬方便加我vx吗，我想请教您
