### ISSUE TITLE
能给一个详细点的用法吗？

### ISSUE THREAD

**Issue by zjcnm** [T3rry7f/Fake115Upload#7]
RT-感谢。

**Comment by zjcnm** [comment]
使用-o命令的时候能不能指定文件夹？

**Comment by zjcnm** [comment]
使用-l filename: 从本地上传一个文件，支持秒传和普通上传两种方式。这种功能的时候提示一下内容怎么办？  -i  -o 这两个都测试成功 还是上传功能只能上传sha1？
[INFO] Trying fast upload...
Traceback (most recent call last):
  File "fake115upload.py", line 259, in <module>
    Upload_file_from_local(v)	
  File "fake115upload.py", line 180, in Upload_file_from_local
    if Upload_localFile_whith_sha1(filename):
  File "fake115upload.py", line 175, in Upload_localFile_whith_sha1
    ret=Upload_file_by_sha1(BlockHASH,TotalHASH,GetFileSize(filename),os.path.basename(filename))
TypeError: Upload_file_by_sha1() takes exactly 5 arguments (4 given)

**Comment by T3rry7f** [comment]
> last

本地上传那边确实有点问题 已经修复了 不过不建议用来上传大文件 因为这功能没有考虑到太多仅仅是简单的实现

**Comment by wywktony** [comment]
> > 持续
> 
> 本地上传那边确实有点问题已经修复了不过不建议使用上传大文件，因为这功能没有考虑到太多明显简单的实现

大佬真心求一个操作方法，填入115

> > 持续
> 
> 本地上传那边确实有点问题已经修复了不过不建议使用上传大文件，因为这功能没有考虑到太多明显简单的实现
大佬真心求一个操作步骤，感谢万千

**Comment by wywktony** [comment]
详细的操作步骤，愿意赞助您，感谢

**Comment by LSD08KM** [comment]
> 详细的操作步骤，愿意赞助您，感谢

我fork了这个项目，欢迎试用
